//
// Created by LN on 2021/1/4.
//

#pragma once
#ifndef TCTS_EDU_APP_RECODER_PLAYER_RESUTL_H
#define TCTS_EDU_APP_RECODER_PLAYER_RESUTL_H

#define  PLAYER_RESULT_OK 1
#define  PLAYER_RESULT_ERROR -1

#endif //TCTS_EDU_APP_RECODER_FFPLAYERBRIDGE_H
